### ISSUE TITLE
No thumbnails when porinting from a sub folder

### ISSUE THREAD

**Issue by luckyzor** [marcolivierarsenault/moonraker-home-assistant#116] opened 2023-04-17 12:41 UTC
## Version of the moonraker integration
last

## Describe your setup

RPI
Klipper, Moonraker, Mainsail

## Describe the bug

when printing from a subfolder the thumbnail will not show

## 
First of all, thanks for this integration, I wich I could have done the same, instead, I've used a rest integration in the config.yaml

I had the same issue with my integration and I solved it by picking the parent_folder of the print and add it to the path if needed
Something like this:

```
       vcore400_parent_file_path:
        friendly_name: "File Parent Path"
        value_template: '{{ states.sensor.vcore400_sensor.attributes["print_stats"]["filename"].split("/")[:-1] |join("/")}}'
       vcore400_url_thumbnail:
         friendly_name: "URL thumbnail Path"
         value_template: '{% if is_state("sensor.vcore400_parent_file_path", "") %}{{ states("sensor.vcore400_object_thumbnails") }}{% else %}{{ states("sensor.vcore400_parent_file_path") }}/{{ states("sensor.vcore400_object_thumbnails") }}{% endif %}'
       vcore400_object_thumbnails:
         friendly_name: "Object Thumbnails"
         value_template: '{{ states.sensor.vcore400_file_metadata.attributes["thumbnails"][1]["relative_path"] }}'
```

maybe this can help you fix this.
I don't know python, but as I see here, I should learn it 😄

**Comment by marcolivierarsenault** [comment] 2023-04-19 21:04
can you show me the result of `http://192.168.2.30/printer/objects/query?print_stats`  change the IP for your printer. 

While you are printing a file from a folder

**Comment by luckyzor** [comment] 2023-04-19 22:53
![photo_2023-04-20_00-21-36](https://user-images.githubusercontent.com/31155573/233216774-242f3746-c3e4-41ba-ab90-12bceb0382a5.jpg)

**Comment by marcolivierarsenault** [comment] 2023-04-20 02:37
I tried to do it on my side and even in mainsail I don't see the thumbnail 
![image](https://user-images.githubusercontent.com/2634090/233242790-c8b2458e-ac05-410b-9a42-4f853b88af84.png)


(I probably do it differently than you) 


Can you:
1) Send me the debug logs for HA-Moonraker while you start a print with a file in a subfolder.
2) Check the metadata of the gcode
`http://192.168.2.30/server/files/metadata?filename=test/CE3E3V2_pi_case_top.gcode` as an example

**Comment by maxcalavera81** [comment] 2023-04-26 12:16
Good. Where can I see the HA-Moonraker debug log?
I have the same problem..

the metadata of the gcode:
{"result": {"size": 1657239, "modified": 1682506945.6086187, "uuid": "3562480e-9eb8-431b-b9e3-2cf07be00f2f", "slicer": "PrusaSlicer", "slicer_version": "2.6.0-alpha6+win64", "gcode_start_byte": 64496, "gcode_end_byte": 1647424, "object_height": 1.44, "estimated_time": 6223, "nozzle_diameter": 0.4, "layer_height": 0.2, "first_layer_height": 0.24, "first_layer_extr_temp": 215.0, "first_layer_bed_temp": 65.0, "filament_name": "Biqu B1 es plus", "filament_type": "PLA", "filament_total": 3781.59, "filament_weight_total": 11.37, "thumbnails": [{"width": 32, "height": 32, "size": 1726, "relative_path": ".thumbs/2verde-32x32.png"}, {"width": 400, "height": 300, "size": 44547, "relative_path": ".thumbs/2verde-400x300.png"}], "print_start_time": 1682508829.838495, "job_id": "000011", "filename": "Sandra/2verde.gcode"}}

In the mainsail thumbnail:

![image](https://user-images.githubusercontent.com/43672635/234571770-445eba54-afb6-41e9-bfa3-fedc5b77f3a0.png)

Thanks.

**Comment by marcolivierarsenault** [comment] 2023-04-26 14:26
@maxcalavera81 can you tell me exactly where is the picture. That might be the issue. 
If you ssh in your device is the picture in 

`xxx/.thumbs/2verde-400x300.png`
or
`xxx/sandra/.thumbs/2verde-400x300.png`

**Comment by marcolivierarsenault** [comment] 2023-04-26 14:41
ok I think I know what the issue is, 

right now we don't append the file prefix, 

I will work on a fix in the next few days

**Comment by maxcalavera81** [comment] 2023-04-26 14:42
> 

Thank you so much for your work, it's just amazing.

**Comment by marcolivierarsenault** [comment] 2023-04-28 00:38
@luckyzor and @maxcalavera81 
We just pushed a patch, can you download the latest code: https://moonraker-home-assistant.readthedocs.io/en/stable/support/latest.html

Get `main`

let me know if this fixes it

**Comment by maxcalavera81** [comment] 2023-04-29 17:31
Don't work here... 
![IMG_20230429_182943](https://user-images.githubusercontent.com/43672635/235316028-585da3e3-1353-47b5-bc40-927e39498539.jpg)

**Comment by marcolivierarsenault** [comment] 2023-04-30 00:47
@maxcalavera81 can you give me some logs, very hard to debug this

**Comment by maxcalavera81** [comment] 2023-05-01 08:32
@marcolivierarsenault Hello, how can I see the debug of the integration? I've already run the HA and I can't find anything about it. Thank you very much

**Comment by luckyzor** [comment] 2023-05-25 07:59
any news about this?

**Comment by marcolivierarsenault** [comment] 2023-05-28 13:26
@maxcalavera81 you can get the log this way https://moonraker-home-assistant.readthedocs.io/en/stable/support/logs.html

**Comment by maxcalavera81** [comment] 2023-06-08 17:39
@marcolivierarsenault Sorry for not giving feedback. Time is not much. But now that I was printing I noticed that it was already working. I have gcode in 2 folders and it works flawlessly. Thank you very much for your work and patience in putting up with us...

![image](https://github.com/marcolivierarsenault/moonraker-home-assistant/assets/43672635/c1e47166-f209-4332-80c0-8634c86d0862)

**Comment by marcolivierarsenault** [comment] 2023-06-08 17:59
@maxcalavera81 so I assume we are good to close this one?

**Comment by maxcalavera81** [comment] 2023-06-08 18:05
@marcolivierarsenault I think so.  At least now it appears... 😄😄

**Closed** 2023-07-02 01:18 UTC
Labels: bug
