### ISSUE TITLE
Websocket connection error when printer is off

### ISSUE THREAD

**Issue by bmos** [marcolivierarsenault/moonraker-home-assistant#278] opened 2024-02-14 14:20 UTC
## Version of the moonraker integration

[1.1.0](https://github.com/marcolivierarsenault/moonraker-home-assistant/releases/tag/1.1.0)

## Describe your setup

Klipper + Mainsail (latest release versions)

## Describe the bug

When my Pi is offline, I get errors in my log:

```
Websocket connection error: Cannot connect to host 192.168.1.247:7125 ssl:default [Connect call failed ('192.168.1.247', 7125)] 
```

It would be great if there was not an error for this as having the device offline some/much of the time is not that surprising. Ideally this would simply set all entities to unavailable.

**Comment by cashew22** [comment] 2024-02-14 14:32
Duplicate of #276, we'll adress that at some point. thanks

**Closed by cashew22** 2024-02-14 14:32 UTC
